### ISSUE TITLE
Unable to cast object of type 'System.Int32' to type 'System.Collections.ArrayList'."

### ISSUE THREAD

**Issue by felixmondelo** [Alachisoft/NCache#30]
Hi, 

We have a replicated cache with 2 nodes, from time to time, we received this error and we aren't able to resolve: "Unable to cast object of type 'System.Int32' to type 'System.Collections.ArrayList'."

The stacktrace:

```
at Alachisoft.NCache.Web.Command.CommandResponse.ParseResponse()
at Alachisoft.NCache.Web.Caching.RemoteCache.Add(String key, Object value, CacheDependency dependency, CacheSyncDependency syncDependency, DateTime absoluteExpiration, TimeSpan slidingExpiration, CacheItemPriority priority, Int16 removeCallback, Int16 updateCallback, Int16 dsItemAddedCallback, Boolean isResyncExpiredItems, String group, String subGroup, Hashtable queryInfo, BitSet flagMap, String providerName, String resyncProviderName, EventDataFilter updateCallbackFilter, EventDataFilter removeCallabackFilter, Int64 size, String clientId)
   at Alachisoft.NCache.Web.Caching.Cache.AddOperation(String key, Object value, CacheDependency dependency, CacheSyncDependency syncDependency, DateTime absoluteExpiration, TimeSpan slidingExpiration, CacheItemPriority priority, DSWriteOption dsWriteOption, CacheItemRemovedCallback onRemoveCallback, CacheItemUpdatedCallback onUpdateCallback, DataSourceItemsAddedCallback onDataSourceItemAdded, Boolean isResyncExpiredItems, String group, String subGroup, Tag[] tags, String providerName, String resyncProviderName, NamedTagsDictionary namedTags, CacheDataNotificationCallback cacheItemUdpatedCallback, CacheDataNotificationCallback cacheItemRemovedCallaback, EventDataFilter itemUpdateDataFilter, EventDataFilter itemRemovedDataFilter, Int64&amp; size, Boolean allowQueryTags, String clientId, Int16 updateCallbackID, Int16 removeCallbackID, Int16 dsItemAddedCallbackID)
   at Alachisoft.NCache.Web.Caching.Cache.Add(String key, CacheItem item, DSWriteOption dsWriteOption, DataSourceItemsAddedCallback onDataSourceItemAdded)
   at Alachisoft.NCache.Web.Caching.Cache.Add(String key, CacheItem item)
```
In the log files we see:

...received response for request 118849, sender=<IP_Server_1>:7800, val=System.Byte[]
...received response for request 118849, sender=<IP_Server_2>:7800, val=Alachisoft.NCache.Common.DataStructures.Clustered.ClusteredArrayList

How can we resolve this problem?

**Comment by Ollie-NCache** [comment]
[FROM OLLIE]

Hello Shirish,

I have looked at your issue and have found out the root cause. The problem is that the Alachisoft.NCache.SDK nuget package does not have some assemblies needed for the view state caching feature to run. There are some dependent assemblies that need to be  copied  in your project bin folder in order to avoid this issue. There are various ways to obtain those assemblies:

1- Install NCache v4.9 SP1 Enterprise edition and select the "Developer" mode when prompted by the installation wizard. This mode does not require a license and completely free. After you have installed it, you will find the required assemblies at %NCHOME%/NCache/Integrations/ContentOptimization, copy them to your application bin folder. Note that %NCHOME% is the path where NCache is installed.

2- Another option could be that you follow the link https://github.com/Alachisoft/NCache/tree/master/Integration/ViewStateCaching and download the solution, compile it and find the required assemblies in the bin/Debug folder.

3- You can also find the assemblies attached in the thread to your query which I have copied from NCache Enterprise installation.

Once those assemblies have been referenced in your project, double check that your web.config file is set with the following directives properly placed as instructed in the Alachisoft documentation (Link: http://www.alachisoft.com/resources/docs/ncache/prog-guide/content-optimization-ncache.html):

```
<add assembly="Alachisoft.NCache.Adapters, **Version=4.9.0.0**, Culture=neutral, PublicKeyToken=CFF5926ED6A53769" />
<add assembly="Alachisoft.Common, Version=4.9.0.0, Culture=neutral, PublicKeyToken=CFF5926ED6A53769" />
<add assembly="Alachisoft.ContentOptimization, Version=4.9.0.0, Culture=neutral, PublicKeyToken=CFF5926ED6A53769" />

```

A working sample is also attached in this thread.

Please let me know if you have any further questions.
[Assemblies.zip](https://github.com/Alachisoft/NCache/files/2658494/Assemblies.zip)
[WorkingSample.zip](https://github.com/Alachisoft/NCache/files/2658495/WorkingSample.zip)

**Comment by Ollie-NCache** [comment]
Hi Felix, 

Thanks for your email. To get to the root of the issue, I will need a couple of pieces of information from you:

1) What version of NCache are you using?
2) Is the NCache installation Enterprise or Open Source?
3) Exact steps to reproduce the problem. A working sample from your end will be great.

This will go through a review and find out what happened.

**Comment by felixmondelo** [comment]
Hi Ollie,

1. Version 4.9.0
2. Open source
3. We don't know :-(, is only after some restarts.

Regards.

**Comment by Ollie-NCache** [comment]
Hi Felix,

If you can attach the client log and the log files from both servers for the times when this error occurred, we'll take a look at them and see if we can reproduce the problem.
The client log can be retrieved from %NCHOME%\NCache\log-files\ClientLogs on the client machine and the server logs can be found at %NCHOME%\NCache\log-files on each server node against the name of the cache. Note that %NCHOME% is the installation directory e.g. C:\Program Files.

**Comment by felixmondelo** [comment]
[NCache.log](https://github.com/Alachisoft/NCache/files/2748545/NCache.log)

**Comment by felixmondelo** [comment]
Hi,

1. Always are Get and Add operations, but the error seems that is on Add operations. The code is:

```
 // Initialize an instance of the cache to begin performing operations:
            _cache = Alachisoft.NCache.Web.Caching.NCache.InitializeCache(cache);

            string queryText = String.Format("SELECT SettingValue FROM dbo.AppSettings WHERE SettingKey = '{0}'", settingKey);

            // Let's create SQL depdenency
            CacheDependency sqlServerDependency = new SqlCacheDependency(SettingsConnectionString, queryText);
            CacheItem cacheItem = new CacheItem(settingValue);
            cacheItem.Dependency = sqlServerDependency;

            string cacheKey = GenerateCacheKey(settingKey);
            _cache.Add(cacheKey, cacheItem);
```
        
2. I attach the client logs.
[ClientLogs..txt](https://github.com/Alachisoft/NCache/files/2806590/ClientLogs.txt)

**Comment by felixmondelo** [comment]
Hi, any ideas?

We have identified how to solve the problem when it happens, but we don't know why it happens from time to time.

When we see this entry in the log:

Alachisoft.NCache.CacheHost.exe              	settingsCache                              	134                                       	INFO     	GroupRequest.doExecute()                received all responses: [GroupRequest:
req_id=816269
members: **172.17.12.179:7800** 172.17.12.177:7800 172.17.12.183:7800 172.17.12.184:7800 172.17.12.185:7800 172.17.12.178:7800 
responses: **System.Byte[]** Alachisoft.NCache.Common.DataStructures.Clustered.ClusteredArrayList Alachisoft.NCache.Common.DataStructures.Clustered.ClusteredArrayList Alachisoft.NCache.Common.DataStructures.Clustered.ClusteredArrayList Alachisoft.NCache.Common.DataStructures.Clustered.ClusteredArrayList Alachisoft.NCache.Common.DataStructures.Clustered.ClusteredArrayList 
request_msg: Alachisoft.NCache.Cluster.Message
rsp_mode: 2
done: False
timeout: 60000
expected_mbrs: 0
]

We know that we have to restart the cache from that node (the node that sends Byte[] instead of ClusteredArrayList) and the NCache began to work as usual.

The error is only for add new values on the cache, if a value is in the cache, we can get it without errors.

Thanks

**Comment by felixmondelo** [comment]
Please, I need a solution urgently... I don't know why from time to time, one of the servers sends Byte[] instead of ClusteredArrayList and why this makes the Add items to the cache, doesn't works.

Please any kind of fix?

**Comment by Brad-NCache** [comment]
Hi Felix,

I have tried to reproduce the scenario you are facing and have also consulted Engineering regarding it but have not been successful so as to come to the root cause of this. This is most probably a network-related issue.

If its possible, we can have a session wherein you can show your environment and produce the behavior so we can analyse it. Please contact support@alachisoft.com and give your contact information so we can set this up.

**Comment by felixmondelo** [comment]
Hi Brad, My email is FMondelo@kabel.es and my phone number is (+34) 609239376. You can contact with me when you want.Thanks and regards
-------- Mensaje original --------De: Brad-NCache <notifications@github.com> Fecha: 25/2/19  20:16  (GMT+01:00) Para: Alachisoft/NCache <NCache@noreply.github.com> Cc: Félix Mondelo <felixmondelo@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [Alachisoft/NCache] Unable to cast object of type 'System.Int32' to type 'System.Collections.ArrayList'." (#30) Hi Felix,
I have tried to reproduce the scenario you are facing and have also consulted Engineering regarding it but have not been successful so as to come to the root cause of this. This is most probably a network-related issue.
If its possible, we can have a session wherein you can show your environment and produce the behavior so we can analyse it. Please contact support@alachisoft.com and give your contact information so we can set this up.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Alachisoft/NCache","title":"Alachisoft/NCache","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Alachisoft/NCache"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Brad-NCache in #30: Hi Felix,\r\n\r\nI have tried to reproduce the scenario you are facing and have also consulted Engineering regarding it but have not been successful so as to come to the root cause of this. This is most probably a network-related issue.\r\n\r\nIf its possible, we can have a session wherein you can show your environment and produce the behavior so we can analyse it. Please contact support@alachisoft.com and give your contact information so we can set this up."}],"action":{"name":"View Issue","url":"https://github.com/Alachisoft/NCache/issues/30#issuecomment-467143518"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Alachisoft/NCache/issues/30#issuecomment-467143518",
"url": "https://github.com/Alachisoft/NCache/issues/30#issuecomment-467143518",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
