### ISSUE TITLE
Error on Get<T>: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0"

### ISSUE THREAD

**Issue by ShoshanaTzi** [Alachisoft/NCache#58]
When calling to `CacheManager.GetCache("mochPartitionedCache").Get<T>(key)`  I'm getting this exception:

`System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Alachisoft.NCache.Client
  StackTrace:
   at Alachisoft.NCache.Client.RemoteCache.SafeDeserialize[T](Object serializedObject, String serializationContext, BitSet flag, CacheImplBase cacheImpl, UserObjectType userObjectType)
   at Alachisoft.NCache.Client.Cache.SafeDeserialize[T](Object serializedObject, String serializationContext, BitSet flag, UserObjectType userObjectType)
   at Alachisoft.NCache.Client.Cache.GetInternal[T](String key, String group, String subGroup, LockAccessType accessType, TimeSpan lockTimeout, LockHandle& lockHandle)
   at Alachisoft.NCache.Client.Cache.Get[T](String key)
   at Ness.Diyur.Cache.DistributedCacheManager.Get[T](String key) in D:\DevProjects\Ness.Diyur.ESB\Ness.Diyur.Cache\DistributedCacheManager.cs:line 20
   at DiyurESB.ServerTest.InfrastructureTests.DistributedCacheTest() in D:\DevProjects\Ness.Diyur.ESB\DiyurESB.ServerTest\InfrastructureTests.cs:line 89
`
I've installed NCache 5.0.3.1 and the Open Source SDK NuGet package. The NCache service is running.
and the Add and Insert method's are working well.

I'm using Newton.Json 12.0.3 for another needed.

What the problem?
Thanks for help

**Comment by Mark-NCache** [comment]
Hi @ShoshanaTzi .

I've sent this to our engineering team and I'll get back to you once I have an update.

Please let me know if there are any questions.

**Comment by ShoshanaTzi** [comment]
Hi,
Thank you for your email.
After I installed the NCache in my local-server, there was no more error


‫בתאריך יום ג׳, 1 בספט׳ 2020 ב-17:33 מאת ‪Mark-NCache‬‏ <‪
notifications@github.com‬‏>:‬
