### ISSUE TITLE
Alachisoft.NCache.Runtime.Exceptions.OperationFailedException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by andrevoltolini** [Alachisoft/NCache#63]
I hope everyone is doing well. I have the following problem:

Exception:
Alachisoft.NCache.Runtime.Exceptions.OperationFailedException: 'Object reference not set to an instance of an object.'
   at Alachisoft.NCache.Client.Broker.RetrySendCommand(CommandBase command)
   at Alachisoft.NCache.Client.Broker.ExecuteRequest(Request request, Connection connection, Boolean checkConnected, Boolean waitForResponse)
   at Alachisoft.NCache.Client.RemoteCache.RegisterNotifications(NotificationsType notifMask, Connection connection)
   at Alachisoft.NCache.Client.Broker.ConnectRemoteServer(Connection connection, IPAddress addr, Int32 port, Boolean balanceNodes, Boolean importHashmap, Boolean registerNotifs, Exception& exception)
   at Alachisoft.NCache.Client.Broker.ConnectRemoteServer(Connection connection, ServerInfo server, Boolean registerNotifs)
   at Alachisoft.NCache.Client.Broker.StartServices(String cacheId, String server, Int32 port)
   at Alachisoft.NCache.Client.RemoteCache..ctor(String cacheId, Cache parent, CacheConnectionOptions cacheConnectionOptions, StatisticsCounter perfStatsCol)
   at Alachisoft.NCache.Client.CacheManager.GetCacheInternal(String cacheName, CacheConnectionOptions cacheConnectionOptions)
   at Alachisoft.NCache.Client.CacheManager.GetCache(String cacheName, CacheConnectionOptions cacheConnectionOptions)

Client version: 5.0.5 (.NET 5) Open source
Server version:  5.0.4.0 Open source

**Comment by Dan-Ahmed** [comment]
Hi @andrevoltolini, 

I believe you are using a higher version of NCache client (5.0 SP5) as compared to the NCache server (v5.0 SP4) which may be causing the issue. It is highly recommended for you to keep the NCache server as well as client in the same version and then test your application with the new NCache setup. 

I hope this clarifies your confusion.

**Comment by andrevoltolini** [comment]
Hi @Dan-Ahmed, thanks for the reply. With the client in version 5.0.4 it works but you agree with me that the object reference exception is a problem in the code. Thanks.
